# Generated by Django 4.1.2 on 2022-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortScanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domainName", models.CharField(max_length=256)),
                ("portRange", models.CharField(max_length=11)),
                ("ipField", models.GenericIPAddressField()),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                ("result", models.TextField()),
            ],
        ),
    ]
