# Generated by Django 4.1.2 on 2022-10-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iascanApp", "0002_portscanner_username_alter_portscanner_scan_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="portscanner", name="username",),
        migrations.AlterField(
            model_name="portscanner",
            name="domainName",
            field=models.CharField(max_length=256, verbose_name="Domain"),
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="ipField",
            field=models.GenericIPAddressField(verbose_name="IP Address"),
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="portRange",
            field=models.CharField(max_length=11, verbose_name="range"),
        ),
    ]
