# Generated by Django 4.1.2 on 2022-10-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iascanApp", "0003_remove_portscanner_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portscanner",
            name="velocityField",
            field=models.CharField(
                choices=[
                    ("T1", "T1"),
                    ("T2", "T2"),
                    ("T3", "T3"),
                    ("T4", "T4"),
                    ("T5", "T5"),
                ],
                default="--",
                max_length=2,
                verbose_name="Port Scan Time",
            ),
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="domainName",
            field=models.CharField(max_length=256, verbose_name="Domain Address"),
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="portRange",
            field=models.CharField(max_length=11, verbose_name="Port Range"),
        ),
    ]
