# Generated by Django 4.1.2 on 2022-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iascanApp", "0004_portscanner_velocityfield_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portscanner",
            name="ipField",
            field=models.GenericIPAddressField(
                default="8.8.8.8", verbose_name="IP Address"
            ),
        ),
    ]
