# Generated by Django 4.1.2 on 2022-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iascanApp", "0005_alter_portscanner_ipfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirBuster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domainName",
                    models.CharField(max_length=256, verbose_name="Domain Address"),
                ),
                (
                    "sslField",
                    models.CharField(
                        choices=[
                            ("SSL Disabled", "SSL Disabled"),
                            ("SSL Enabled", "SSL Enabled"),
                        ],
                        default="SSL Enabled",
                        max_length=14,
                        verbose_name="SSL Certificate",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="portscanner",
            name="velocityField",
            field=models.CharField(
                choices=[
                    ("T1", "T1"),
                    ("T2", "T2"),
                    ("T3", "T3"),
                    ("T4", "T4"),
                    ("T5", "T5"),
                ],
                default="T5",
                max_length=2,
                verbose_name="Port Scan Time",
            ),
        ),
    ]
