# Generated by Django 4.1.3 on 2022-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iascanApp", "0007_rename_result_portscanner_banners_portscanner_ports"),
    ]

    operations = [
        migrations.RemoveField(model_name="portscanner", name="portRange",),
        migrations.AddField(
            model_name="portscanner",
            name="endPort",
            field=models.CharField(default=-1, max_length=5, verbose_name="Start Port"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portscanner",
            name="startPort",
            field=models.CharField(
                default=0, max_length=5, verbose_name="Start Port (0-65565)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dirbuster",
            name="domainName",
            field=models.CharField(
                max_length=256, verbose_name="Domain Address (ex: google.com"
            ),
        ),
    ]
